### PR TITLE
Bump to v0.1.4

### PR DESCRIPTION
**Pull request by ikehz**
Block on #2 and #4.

### CODE REVIEW

**Comment by ikehz** [comment]
Xref https://github.com/kubernetes/kubernetes/pull/54653.

**Comment by ikehz** [comment]
Let's not block this on #2, since kubernetes/kubernetes#52744 isn't in yet.

**Review by destijl — COMMENTED** [review]
/lgtm

**Comment by ikehz** [comment]
```
$ make push
rm -f metadata_proxy
go get github.com/tools/godep
godep save
GOOS=linux GOARCH=amd64 CGO_ENABLED=0 godep go test ./...
?       github.com/GoogleCloudPlatform/k8s-metadata-proxy       [no test files]
?       github.com/GoogleCloudPlatform/k8s-metadata-proxy/metrics       [no test files]
?       github.com/GoogleCloudPlatform/k8s-metadata-proxy/test  [no test files]
GOOS=linux GOARCH=amd64 CGO_ENABLED=0 godep go build -o metadata_proxy
docker build --pull --no-cache -t gcr.io/google_containers/metadata-proxy:v0.1.4 .
Sending build context to Docker daemon 10.29 MB
Step 1 : FROM gcr.io/google_containers/debian-base-amd64:0.1
0.1: Pulling from google_containers/debian-base-amd64
Digest: sha256:e7248990914c1cfbaef526332bb72064819a08b513f6a87f228f82155b7714ac
Status: Image is up to date for gcr.io/google_containers/debian-base-amd64:0.1
 ---> be4292fc517f
Step 2 : LABEL maintainer "ihmccreery@google.com"
 ---> Running in fd9133daa214
 ---> 518f6e2b0fd6
Removing intermediate container fd9133daa214
Step 3 : ARG DEBIAN_FRONTEND=noninteractive
 ---> Running in 2820a1a7968e
 ---> 62ceb4c6fe3b
Removing intermediate container 2820a1a7968e
Step 4 : RUN apt-get update && apt-get install -y   apt-utils && clean-install iptables
 ---> Running in c437ee88f496
Get:1 http://security.debian.org jessie/updates InRelease [63.1 kB]
Ign http://deb.debian.org jessie InRelease
Get:2 http://deb.debian.org jessie-updates InRelease [145 kB]
Get:3 http://security.debian.org jessie/updates/main amd64 Packages [548 kB]
Get:4 http://deb.debian.org jessie Release.gpg [2373 B]
Get:5 http://deb.debian.org jessie Release [148 kB]
Get:6 http://deb.debian.org jessie-updates/main amd64 Packages [23.2 kB]
Get:7 http://deb.debian.org jessie/main amd64 Packages [9063 kB]
Fetched 9994 kB in 3s (3132 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  libapt-inst1.5
The following NEW packages will be installed:
  apt-utils libapt-inst1.5
0 upgraded, 2 newly installed, 0 to remove and 8 not upgraded.
Need to get 537 kB of archives.
After this operation, 1333 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian/ jessie/main libapt-inst1.5 amd64 1.0.9.8.4 [169 kB]
Get:2 http://deb.debian.org/debian/ jessie/main apt-utils amd64 1.0.9.8.4 [368 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 537 kB in 0s (1523 kB/s)
Selecting previously unselected package libapt-inst1.5:amd64.
(Reading database ... 3949 files and directories currently installed.)
Preparing to unpack .../libapt-inst1.5_1.0.9.8.4_amd64.deb ...
Unpacking libapt-inst1.5:amd64 (1.0.9.8.4) ...
Selecting previously unselected package apt-utils.
Preparing to unpack .../apt-utils_1.0.9.8.4_amd64.deb ...
Unpacking apt-utils (1.0.9.8.4) ...
Setting up libapt-inst1.5:amd64 (1.0.9.8.4) ...
Setting up apt-utils (1.0.9.8.4) ...
Processing triggers for libc-bin (2.19-18+deb8u10) ...
Hit http://security.debian.org jessie/updates InRelease
Ign http://deb.debian.org jessie InRelease
Hit http://deb.debian.org jessie-updates InRelease
Get:1 http://security.debian.org jessie/updates/main amd64 Packages [548 kB]
Hit http://deb.debian.org jessie Release.gpg
Hit http://deb.debian.org jessie Release
Get:2 http://deb.debian.org jessie-updates/main amd64 Packages [23.2 kB]
Get:3 http://deb.debian.org jessie/main amd64 Packages [9063 kB]
Fetched 9635 kB in 3s (3038 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  libnfnetlink0 libxtables10
The following NEW packages will be installed:
  iptables libnfnetlink0 libxtables10
0 upgraded, 3 newly installed, 0 to remove and 8 not upgraded.
Need to get 358 kB of archives.
After this operation, 3818 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian/ jessie/main libnfnetlink0 amd64 1.0.1-3 [13.5 kB]
Get:2 http://deb.debian.org/debian/ jessie/main libxtables10 amd64 1.4.21-2+b1 [67.6 kB]
Get:3 http://deb.debian.org/debian/ jessie/main iptables amd64 1.4.21-2+b1 [277 kB]
Fetched 358 kB in 0s (490 kB/s)
Selecting previously unselected package libnfnetlink0:amd64.
(Reading database ... 4076 files and directories currently installed.)
Preparing to unpack .../libnfnetlink0_1.0.1-3_amd64.deb ...
Unpacking libnfnetlink0:amd64 (1.0.1-3) ...
Selecting previously unselected package libxtables10.
Preparing to unpack .../libxtables10_1.4.21-2+b1_amd64.deb ...
Unpacking libxtables10 (1.4.21-2+b1) ...
Selecting previously unselected package iptables.
Preparing to unpack .../iptables_1.4.21-2+b1_amd64.deb ...
Unpacking iptables (1.4.21-2+b1) ...
Setting up libnfnetlink0:amd64 (1.0.1-3) ...
Setting up libxtables10 (1.4.21-2+b1) ...
Setting up iptables (1.4.21-2+b1) ...
Processing triggers for libc-bin (2.19-18+deb8u10) ...
 ---> 9fbba94fa0e0
Removing intermediate container c437ee88f496
Step 5 : COPY start-proxy.sh /
 ---> ca2f5bb7ff0b
Removing intermediate container dbd451f2d283
Step 6 : COPY metadata_proxy /
 ---> 78f10aec4972
Removing intermediate container 77e0b732d7ff
Step 7 : ENTRYPOINT /start-proxy.sh
 ---> Running in b38171e91e0a
 ---> 77dd1c74b7ce
Removing intermediate container b38171e91e0a
Successfully built 77dd1c74b7ce
gcloud docker -- push gcr.io/google_containers/metadata-proxy:v0.1.4
The push refers to a repository [gcr.io/google_containers/metadata-proxy]
5993fcc4cf83: Pushed 
34821ce034be: Pushed 
0dbcd6a1282f: Pushed 
d066a55459dd: Layer already exists 
v0.1.4: digest: sha256:9ca02cc773e286b28942103e2482ce74e281ef2c18936610d379b26ecb89c533 size: 1157
```

**Pull request merged**
