### PR TITLE
Remove start-proxy.sh

### PR DESCRIPTION
**Pull request by ikehz**
Let startup scripts do iptables magic instead of the proxy.

### CODE REVIEW

**Comment by ikehz** [comment]
This isn't secure, since the ability to bind to a port could lead to being able to serve fake credentials to other pods.

**Comment by ikehz** [comment]
This actually isn't a privilege escalation path, because port 988 is a well-known port and can only be bound to with root privileges.

**Comment by ikehz** [comment]
Xref https://github.com/kubernetes/kubernetes/pull/55360

**Comment by mikedanese** [comment]
> Let startup scripts do iptables magic instead of the proxy.

Why is this more desirable?

**Comment by ikehz** [comment]
> Why is this more desirable?

We can shrink the container to a smaller image (SCRATCH instead of debian).  And, right now if the proxy restarts it duplicates rules.

**Pull request merged**
