### PR TITLE
Add Google Container Builder config for k8s-metadata-proxy

### PR DESCRIPTION
**Pull request by rvkubiak**
GCB config to be used to automate build of Kubernetes addon images.

### CODE REVIEW

**Comment by mikedanese** [comment]
@rvkubiak can you have someone from your team LGTM this? We don't have the expertise to review a change like this.

**Comment by rvkubiak** [comment]
@mikedanese Sure, in fact I think we're going to end up closing these PRs and just submitting them to their own repo.  I've since transferred projects so waiting to hear on the final details, but I imagine I'll close this out soon.

**Comment by mikedanese** [comment]
SGTM, let me know if you need anything.

**Comment by rvkubiak** [comment]
Moving these configs to their own repo.

**Pull request closed without merging**
