### PR TITLE
Rebase k8s images to distroless.

### PR DESCRIPTION
**Pull request by yuwenma**
This is part of the effort described in KEP kubernetes/enhancements#900

### CODE REVIEW

**Comment by dekkagaijin** [comment]
Will `gcr.io/distroless/static` ever be updated? Is there a stable tag available?

**Comment by yuwenma** [comment]
It will and it does have stable tags. We previously have a discussion about using "latest" or a specific tag. I think the conclusion is that as a tradeoff between extra manual effort on updating the tags periodically vs. ignoring the base image version reason on triaging a problem, we prefer the latter. Is it reasonable on your side?

**Comment by dekkagaijin** [comment]
Normally I'd say that it's always correct to pin the base image to a stable tag (or, better yet, a digest). Given that the spirit of this image is to be usefully minimal, and that the distroless repo itself seems to recommend `latest`, I'm OK with it

**Pull request merged**
